### ISSUE TITLE
r-blogger code incomplete

### ISSUE THREAD

**Issue by dxbhans** [StatsGary/MakeSQLTableFunction#1]
Hi Gary, on my browser (Safari, iOS 14) the function code does not fulltime appear on the r-blogger post.

**Comment by StatsGary** [comment]
Unsure why this is. Can you link to the actual blog post, as the RSS between my site and Rbloggers has been established for a while. Best Gary

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Hans Meijer ***@***.***>
Sent: Thursday, March 11, 2021 1:08:58 AM
To: StatsGary/MakeSQLTableFunction ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StatsGary/MakeSQLTableFunction] r-blogger code incomplete (#1)


Hi Gary, on my browser (Safari, iOS 14) the function code does not fulltime appear on the r-blogger post.
